# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AnalyzeTextEntityLinkingInput
    from ._models_py3 import AnalyzeTextEntityRecognitionInput
    from ._models_py3 import AnalyzeTextJobState
    from ._models_py3 import AnalyzeTextJobStatistics
    from ._models_py3 import AnalyzeTextJobsInput
    from ._models_py3 import AnalyzeTextJobsInputTasksItem
    from ._models_py3 import AnalyzeTextKeyPhraseExtractionInput
    from ._models_py3 import AnalyzeTextLROResult
    from ._models_py3 import AnalyzeTextLanguageDetectionInput
    from ._models_py3 import AnalyzeTextPiiEntitiesRecognitionInput
    from ._models_py3 import AnalyzeTextSentimentAnalysisInput
    from ._models_py3 import AnalyzeTextTask
    from ._models_py3 import AnalyzeTextTaskResult
    from ._models_py3 import ClassificationResult
    from ._models_py3 import CustomEntitiesResult
    from ._models_py3 import CustomEntitiesResultDocumentsItem
    from ._models_py3 import CustomEntitiesTask
    from ._models_py3 import CustomEntitiesTaskParameters
    from ._models_py3 import CustomEntityRecognitionLROResult
    from ._models_py3 import CustomMultiClassificationLROResult
    from ._models_py3 import CustomMultiClassificationResult
    from ._models_py3 import CustomMultiClassificationResultDocumentsItem
    from ._models_py3 import CustomMultiClassificationTask
    from ._models_py3 import CustomMultiClassificationTaskParameters
    from ._models_py3 import CustomResult
    from ._models_py3 import CustomSingleClassificationLROResult
    from ._models_py3 import CustomSingleClassificationResult
    from ._models_py3 import CustomSingleClassificationResultDocumentsItem
    from ._models_py3 import CustomSingleClassificationTask
    from ._models_py3 import CustomSingleClassificationTaskParameters
    from ._models_py3 import CustomTaskParameters
    from ._models_py3 import DetectedLanguage
    from ._models_py3 import DocumentDetectedLanguage
    from ._models_py3 import DocumentError
    from ._models_py3 import DocumentResult
    from ._models_py3 import DocumentStatistics
    from ._models_py3 import DocumentWarning
    from ._models_py3 import EntitiesDocumentResult
    from ._models_py3 import EntitiesResult
    from ._models_py3 import EntitiesResultDocumentsItem
    from ._models_py3 import EntitiesTask
    from ._models_py3 import EntitiesTaskParameters
    from ._models_py3 import EntitiesTaskParametersAutoGenerated
    from ._models_py3 import EntitiesTaskResult
    from ._models_py3 import Entity
    from ._models_py3 import EntityLinkingLROResult
    from ._models_py3 import EntityLinkingResult
    from ._models_py3 import EntityLinkingResultDocumentsItem
    from ._models_py3 import EntityLinkingTask
    from ._models_py3 import EntityLinkingTaskParameters
    from ._models_py3 import EntityLinkingTaskParametersAutoGenerated
    from ._models_py3 import EntityLinkingTaskResult
    from ._models_py3 import EntityRecognitionLROResult
    from ._models_py3 import Error
    from ._models_py3 import ErrorResponse
    from ._models_py3 import ExtractedSummaryDocumentResult
    from ._models_py3 import ExtractedSummarySentence
    from ._models_py3 import ExtractiveSummarizationLROResult
    from ._models_py3 import ExtractiveSummarizationResult
    from ._models_py3 import ExtractiveSummarizationResultDocumentsItem
    from ._models_py3 import ExtractiveSummarizationTask
    from ._models_py3 import ExtractiveSummarizationTaskParameters
    from ._models_py3 import ExtractiveSummarizationTaskParametersAutoGenerated
    from ._models_py3 import HealthcareAssertion
    from ._models_py3 import HealthcareEntitiesDocumentResult
    from ._models_py3 import HealthcareEntity
    from ._models_py3 import HealthcareEntityLink
    from ._models_py3 import HealthcareEntityProperties
    from ._models_py3 import HealthcareLROResult
    from ._models_py3 import HealthcareLinkingProperties
    from ._models_py3 import HealthcareRelation
    from ._models_py3 import HealthcareRelationEntity
    from ._models_py3 import HealthcareResult
    from ._models_py3 import HealthcareResultDocumentsItem
    from ._models_py3 import HealthcareTask
    from ._models_py3 import HealthcareTaskParameters
    from ._models_py3 import HealthcareTaskParametersAutoGenerated
    from ._models_py3 import InnerErrorModel
    from ._models_py3 import JobErrors
    from ._models_py3 import JobMetadata
    from ._models_py3 import JobState
    from ._models_py3 import KeyPhraseExtractionLROResult
    from ._models_py3 import KeyPhraseResult
    from ._models_py3 import KeyPhraseResultDocumentsItem
    from ._models_py3 import KeyPhraseTask
    from ._models_py3 import KeyPhraseTaskParameters
    from ._models_py3 import KeyPhraseTaskResult
    from ._models_py3 import KeyPhrasesDocumentResult
    from ._models_py3 import LanguageBatchInput
    from ._models_py3 import LanguageDetectionAnalysisInput
    from ._models_py3 import LanguageDetectionDocumentResult
    from ._models_py3 import LanguageDetectionResult
    from ._models_py3 import LanguageDetectionTask
    from ._models_py3 import LanguageDetectionTaskParameters
    from ._models_py3 import LanguageDetectionTaskParametersAutoGenerated
    from ._models_py3 import LanguageDetectionTaskResult
    from ._models_py3 import LanguageInput
    from ._models_py3 import LinkedEntitiesDocumentResult
    from ._models_py3 import LinkedEntity
    from ._models_py3 import Match
    from ._models_py3 import MultiClassificationDocumentResult
    from ._models_py3 import MultiLanguageAnalysisInput
    from ._models_py3 import MultiLanguageBatchInput
    from ._models_py3 import MultiLanguageInput
    from ._models_py3 import Pagination
    from ._models_py3 import PiiEntitiesDocumentResult
    from ._models_py3 import PiiEntityRecognitionLROResult
    from ._models_py3 import PiiResult
    from ._models_py3 import PiiResultDocumentsItem
    from ._models_py3 import PiiTask
    from ._models_py3 import PiiTaskParameters
    from ._models_py3 import PiiTaskParametersAutoGenerated
    from ._models_py3 import PiiTaskResult
    from ._models_py3 import PreBuiltResult
    from ._models_py3 import PreBuiltTaskParameters
    from ._models_py3 import RequestStatistics
    from ._models_py3 import SentenceAssessment
    from ._models_py3 import SentenceSentiment
    from ._models_py3 import SentenceTarget
    from ._models_py3 import SentimentAnalysisTask
    from ._models_py3 import SentimentAnalysisTaskParameters
    from ._models_py3 import SentimentAnalysisTaskParametersAutoGenerated
    from ._models_py3 import SentimentConfidenceScorePerLabel
    from ._models_py3 import SentimentDocumentResult
    from ._models_py3 import SentimentLROResult
    from ._models_py3 import SentimentResponse
    from ._models_py3 import SentimentResponseDocumentsItem
    from ._models_py3 import SentimentTaskResult
    from ._models_py3 import SingleClassificationDocumentResult
    from ._models_py3 import TargetConfidenceScoreLabel
    from ._models_py3 import TargetRelation
    from ._models_py3 import TaskIdentifier
    from ._models_py3 import TaskParameters
    from ._models_py3 import TaskState
    from ._models_py3 import TasksState
    from ._models_py3 import TasksStateTasks
except (SyntaxError, ImportError):
    from ._models import AnalyzeTextEntityLinkingInput  # type: ignore
    from ._models import AnalyzeTextEntityRecognitionInput  # type: ignore
    from ._models import AnalyzeTextJobState  # type: ignore
    from ._models import AnalyzeTextJobStatistics  # type: ignore
    from ._models import AnalyzeTextJobsInput  # type: ignore
    from ._models import AnalyzeTextJobsInputTasksItem  # type: ignore
    from ._models import AnalyzeTextKeyPhraseExtractionInput  # type: ignore
    from ._models import AnalyzeTextLROResult  # type: ignore
    from ._models import AnalyzeTextLanguageDetectionInput  # type: ignore
    from ._models import AnalyzeTextPiiEntitiesRecognitionInput  # type: ignore
    from ._models import AnalyzeTextSentimentAnalysisInput  # type: ignore
    from ._models import AnalyzeTextTask  # type: ignore
    from ._models import AnalyzeTextTaskResult  # type: ignore
    from ._models import ClassificationResult  # type: ignore
    from ._models import CustomEntitiesResult  # type: ignore
    from ._models import CustomEntitiesResultDocumentsItem  # type: ignore
    from ._models import CustomEntitiesTask  # type: ignore
    from ._models import CustomEntitiesTaskParameters  # type: ignore
    from ._models import CustomEntityRecognitionLROResult  # type: ignore
    from ._models import CustomMultiClassificationLROResult  # type: ignore
    from ._models import CustomMultiClassificationResult  # type: ignore
    from ._models import CustomMultiClassificationResultDocumentsItem  # type: ignore
    from ._models import CustomMultiClassificationTask  # type: ignore
    from ._models import CustomMultiClassificationTaskParameters  # type: ignore
    from ._models import CustomResult  # type: ignore
    from ._models import CustomSingleClassificationLROResult  # type: ignore
    from ._models import CustomSingleClassificationResult  # type: ignore
    from ._models import CustomSingleClassificationResultDocumentsItem  # type: ignore
    from ._models import CustomSingleClassificationTask  # type: ignore
    from ._models import CustomSingleClassificationTaskParameters  # type: ignore
    from ._models import CustomTaskParameters  # type: ignore
    from ._models import DetectedLanguage  # type: ignore
    from ._models import DocumentDetectedLanguage  # type: ignore
    from ._models import DocumentError  # type: ignore
    from ._models import DocumentResult  # type: ignore
    from ._models import DocumentStatistics  # type: ignore
    from ._models import DocumentWarning  # type: ignore
    from ._models import EntitiesDocumentResult  # type: ignore
    from ._models import EntitiesResult  # type: ignore
    from ._models import EntitiesResultDocumentsItem  # type: ignore
    from ._models import EntitiesTask  # type: ignore
    from ._models import EntitiesTaskParameters  # type: ignore
    from ._models import EntitiesTaskParametersAutoGenerated  # type: ignore
    from ._models import EntitiesTaskResult  # type: ignore
    from ._models import Entity  # type: ignore
    from ._models import EntityLinkingLROResult  # type: ignore
    from ._models import EntityLinkingResult  # type: ignore
    from ._models import EntityLinkingResultDocumentsItem  # type: ignore
    from ._models import EntityLinkingTask  # type: ignore
    from ._models import EntityLinkingTaskParameters  # type: ignore
    from ._models import EntityLinkingTaskParametersAutoGenerated  # type: ignore
    from ._models import EntityLinkingTaskResult  # type: ignore
    from ._models import EntityRecognitionLROResult  # type: ignore
    from ._models import Error  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import ExtractedSummaryDocumentResult  # type: ignore
    from ._models import ExtractedSummarySentence  # type: ignore
    from ._models import ExtractiveSummarizationLROResult  # type: ignore
    from ._models import ExtractiveSummarizationResult  # type: ignore
    from ._models import ExtractiveSummarizationResultDocumentsItem  # type: ignore
    from ._models import ExtractiveSummarizationTask  # type: ignore
    from ._models import ExtractiveSummarizationTaskParameters  # type: ignore
    from ._models import ExtractiveSummarizationTaskParametersAutoGenerated  # type: ignore
    from ._models import HealthcareAssertion  # type: ignore
    from ._models import HealthcareEntitiesDocumentResult  # type: ignore
    from ._models import HealthcareEntity  # type: ignore
    from ._models import HealthcareEntityLink  # type: ignore
    from ._models import HealthcareEntityProperties  # type: ignore
    from ._models import HealthcareLROResult  # type: ignore
    from ._models import HealthcareLinkingProperties  # type: ignore
    from ._models import HealthcareRelation  # type: ignore
    from ._models import HealthcareRelationEntity  # type: ignore
    from ._models import HealthcareResult  # type: ignore
    from ._models import HealthcareResultDocumentsItem  # type: ignore
    from ._models import HealthcareTask  # type: ignore
    from ._models import HealthcareTaskParameters  # type: ignore
    from ._models import HealthcareTaskParametersAutoGenerated  # type: ignore
    from ._models import InnerErrorModel  # type: ignore
    from ._models import JobErrors  # type: ignore
    from ._models import JobMetadata  # type: ignore
    from ._models import JobState  # type: ignore
    from ._models import KeyPhraseExtractionLROResult  # type: ignore
    from ._models import KeyPhraseResult  # type: ignore
    from ._models import KeyPhraseResultDocumentsItem  # type: ignore
    from ._models import KeyPhraseTask  # type: ignore
    from ._models import KeyPhraseTaskParameters  # type: ignore
    from ._models import KeyPhraseTaskResult  # type: ignore
    from ._models import KeyPhrasesDocumentResult  # type: ignore
    from ._models import LanguageBatchInput  # type: ignore
    from ._models import LanguageDetectionAnalysisInput  # type: ignore
    from ._models import LanguageDetectionDocumentResult  # type: ignore
    from ._models import LanguageDetectionResult  # type: ignore
    from ._models import LanguageDetectionTask  # type: ignore
    from ._models import LanguageDetectionTaskParameters  # type: ignore
    from ._models import LanguageDetectionTaskParametersAutoGenerated  # type: ignore
    from ._models import LanguageDetectionTaskResult  # type: ignore
    from ._models import LanguageInput  # type: ignore
    from ._models import LinkedEntitiesDocumentResult  # type: ignore
    from ._models import LinkedEntity  # type: ignore
    from ._models import Match  # type: ignore
    from ._models import MultiClassificationDocumentResult  # type: ignore
    from ._models import MultiLanguageAnalysisInput  # type: ignore
    from ._models import MultiLanguageBatchInput  # type: ignore
    from ._models import MultiLanguageInput  # type: ignore
    from ._models import Pagination  # type: ignore
    from ._models import PiiEntitiesDocumentResult  # type: ignore
    from ._models import PiiEntityRecognitionLROResult  # type: ignore
    from ._models import PiiResult  # type: ignore
    from ._models import PiiResultDocumentsItem  # type: ignore
    from ._models import PiiTask  # type: ignore
    from ._models import PiiTaskParameters  # type: ignore
    from ._models import PiiTaskParametersAutoGenerated  # type: ignore
    from ._models import PiiTaskResult  # type: ignore
    from ._models import PreBuiltResult  # type: ignore
    from ._models import PreBuiltTaskParameters  # type: ignore
    from ._models import RequestStatistics  # type: ignore
    from ._models import SentenceAssessment  # type: ignore
    from ._models import SentenceSentiment  # type: ignore
    from ._models import SentenceTarget  # type: ignore
    from ._models import SentimentAnalysisTask  # type: ignore
    from ._models import SentimentAnalysisTaskParameters  # type: ignore
    from ._models import SentimentAnalysisTaskParametersAutoGenerated  # type: ignore
    from ._models import SentimentConfidenceScorePerLabel  # type: ignore
    from ._models import SentimentDocumentResult  # type: ignore
    from ._models import SentimentLROResult  # type: ignore
    from ._models import SentimentResponse  # type: ignore
    from ._models import SentimentResponseDocumentsItem  # type: ignore
    from ._models import SentimentTaskResult  # type: ignore
    from ._models import SingleClassificationDocumentResult  # type: ignore
    from ._models import TargetConfidenceScoreLabel  # type: ignore
    from ._models import TargetRelation  # type: ignore
    from ._models import TaskIdentifier  # type: ignore
    from ._models import TaskParameters  # type: ignore
    from ._models import TaskState  # type: ignore
    from ._models import TasksState  # type: ignore
    from ._models import TasksStateTasks  # type: ignore

from ._microsoft_cognitive_language_service_enums import (
    AnalyzeTextLROResultsKind,
    AnalyzeTextTaskKind,
    AnalyzeTextTaskResultsKind,
    Association,
    Certainty,
    Conditionality,
    DocumentSentimentValue,
    ErrorCode,
    ExtractiveSummarizationSortingCriteria,
    HealthcareEntityCategory,
    InnerErrorCode,
    PiiCategory,
    PiiDomain,
    RelationType,
    SentenceSentimentValue,
    State,
    StringIndexType,
    TargetRelationType,
    TokenSentimentValue,
    WarningCodeValue,
)

__all__ = [
    'AnalyzeTextEntityLinkingInput',
    'AnalyzeTextEntityRecognitionInput',
    'AnalyzeTextJobState',
    'AnalyzeTextJobStatistics',
    'AnalyzeTextJobsInput',
    'AnalyzeTextJobsInputTasksItem',
    'AnalyzeTextKeyPhraseExtractionInput',
    'AnalyzeTextLROResult',
    'AnalyzeTextLanguageDetectionInput',
    'AnalyzeTextPiiEntitiesRecognitionInput',
    'AnalyzeTextSentimentAnalysisInput',
    'AnalyzeTextTask',
    'AnalyzeTextTaskResult',
    'ClassificationResult',
    'CustomEntitiesResult',
    'CustomEntitiesResultDocumentsItem',
    'CustomEntitiesTask',
    'CustomEntitiesTaskParameters',
    'CustomEntityRecognitionLROResult',
    'CustomMultiClassificationLROResult',
    'CustomMultiClassificationResult',
    'CustomMultiClassificationResultDocumentsItem',
    'CustomMultiClassificationTask',
    'CustomMultiClassificationTaskParameters',
    'CustomResult',
    'CustomSingleClassificationLROResult',
    'CustomSingleClassificationResult',
    'CustomSingleClassificationResultDocumentsItem',
    'CustomSingleClassificationTask',
    'CustomSingleClassificationTaskParameters',
    'CustomTaskParameters',
    'DetectedLanguage',
    'DocumentDetectedLanguage',
    'DocumentError',
    'DocumentResult',
    'DocumentStatistics',
    'DocumentWarning',
    'EntitiesDocumentResult',
    'EntitiesResult',
    'EntitiesResultDocumentsItem',
    'EntitiesTask',
    'EntitiesTaskParameters',
    'EntitiesTaskParametersAutoGenerated',
    'EntitiesTaskResult',
    'Entity',
    'EntityLinkingLROResult',
    'EntityLinkingResult',
    'EntityLinkingResultDocumentsItem',
    'EntityLinkingTask',
    'EntityLinkingTaskParameters',
    'EntityLinkingTaskParametersAutoGenerated',
    'EntityLinkingTaskResult',
    'EntityRecognitionLROResult',
    'Error',
    'ErrorResponse',
    'ExtractedSummaryDocumentResult',
    'ExtractedSummarySentence',
    'ExtractiveSummarizationLROResult',
    'ExtractiveSummarizationResult',
    'ExtractiveSummarizationResultDocumentsItem',
    'ExtractiveSummarizationTask',
    'ExtractiveSummarizationTaskParameters',
    'ExtractiveSummarizationTaskParametersAutoGenerated',
    'HealthcareAssertion',
    'HealthcareEntitiesDocumentResult',
    'HealthcareEntity',
    'HealthcareEntityLink',
    'HealthcareEntityProperties',
    'HealthcareLROResult',
    'HealthcareLinkingProperties',
    'HealthcareRelation',
    'HealthcareRelationEntity',
    'HealthcareResult',
    'HealthcareResultDocumentsItem',
    'HealthcareTask',
    'HealthcareTaskParameters',
    'HealthcareTaskParametersAutoGenerated',
    'InnerErrorModel',
    'JobErrors',
    'JobMetadata',
    'JobState',
    'KeyPhraseExtractionLROResult',
    'KeyPhraseResult',
    'KeyPhraseResultDocumentsItem',
    'KeyPhraseTask',
    'KeyPhraseTaskParameters',
    'KeyPhraseTaskResult',
    'KeyPhrasesDocumentResult',
    'LanguageBatchInput',
    'LanguageDetectionAnalysisInput',
    'LanguageDetectionDocumentResult',
    'LanguageDetectionResult',
    'LanguageDetectionTask',
    'LanguageDetectionTaskParameters',
    'LanguageDetectionTaskParametersAutoGenerated',
    'LanguageDetectionTaskResult',
    'LanguageInput',
    'LinkedEntitiesDocumentResult',
    'LinkedEntity',
    'Match',
    'MultiClassificationDocumentResult',
    'MultiLanguageAnalysisInput',
    'MultiLanguageBatchInput',
    'MultiLanguageInput',
    'Pagination',
    'PiiEntitiesDocumentResult',
    'PiiEntityRecognitionLROResult',
    'PiiResult',
    'PiiResultDocumentsItem',
    'PiiTask',
    'PiiTaskParameters',
    'PiiTaskParametersAutoGenerated',
    'PiiTaskResult',
    'PreBuiltResult',
    'PreBuiltTaskParameters',
    'RequestStatistics',
    'SentenceAssessment',
    'SentenceSentiment',
    'SentenceTarget',
    'SentimentAnalysisTask',
    'SentimentAnalysisTaskParameters',
    'SentimentAnalysisTaskParametersAutoGenerated',
    'SentimentConfidenceScorePerLabel',
    'SentimentDocumentResult',
    'SentimentLROResult',
    'SentimentResponse',
    'SentimentResponseDocumentsItem',
    'SentimentTaskResult',
    'SingleClassificationDocumentResult',
    'TargetConfidenceScoreLabel',
    'TargetRelation',
    'TaskIdentifier',
    'TaskParameters',
    'TaskState',
    'TasksState',
    'TasksStateTasks',
    'AnalyzeTextLROResultsKind',
    'AnalyzeTextTaskKind',
    'AnalyzeTextTaskResultsKind',
    'Association',
    'Certainty',
    'Conditionality',
    'DocumentSentimentValue',
    'ErrorCode',
    'ExtractiveSummarizationSortingCriteria',
    'HealthcareEntityCategory',
    'InnerErrorCode',
    'PiiCategory',
    'PiiDomain',
    'RelationType',
    'SentenceSentimentValue',
    'State',
    'StringIndexType',
    'TargetRelationType',
    'TokenSentimentValue',
    'WarningCodeValue',
]
