# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models import AudioTranscription
from ._models import AudioTranscriptionSegment
from ._models import AudioTranslation
from ._models import AudioTranslationSegment
from ._models import AzureChatExtensionConfiguration
from ._models import AzureChatExtensionsMessageContext
from ._models import ChatChoice
from ._models import ChatCompletions
from ._models import ChatMessage
from ._models import Choice
from ._models import Completions
from ._models import CompletionsLogProbabilityModel
from ._models import CompletionsUsage
from ._models import ContentFilterResult
from ._models import ContentFilterResults
from ._models import EmbeddingItem
from ._models import Embeddings
from ._models import EmbeddingsUsage
from ._models import FunctionCall
from ._models import FunctionDefinition
from ._models import FunctionName
from ._models import ImageGenerations
from ._models import ImageLocation
from ._models import ImagePayload
from ._models import PromptFilterResult

from ._enums import AudioTaskLabel
from ._enums import AudioTranscriptionFormat
from ._enums import AudioTranslationFormat
from ._enums import AzureChatExtensionType
from ._enums import ChatRole
from ._enums import CompletionsFinishReason
from ._enums import ContentFilterSeverity
from ._enums import FunctionCallPreset
from ._enums import ImageGenerationResponseFormat
from ._enums import ImageSize
from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "AudioTranscription",
    "AudioTranscriptionSegment",
    "AudioTranslation",
    "AudioTranslationSegment",
    "AzureChatExtensionConfiguration",
    "AzureChatExtensionsMessageContext",
    "ChatChoice",
    "ChatCompletions",
    "ChatMessage",
    "Choice",
    "Completions",
    "CompletionsLogProbabilityModel",
    "CompletionsUsage",
    "ContentFilterResult",
    "ContentFilterResults",
    "EmbeddingItem",
    "Embeddings",
    "EmbeddingsUsage",
    "FunctionCall",
    "FunctionDefinition",
    "FunctionName",
    "ImageGenerations",
    "ImageLocation",
    "ImagePayload",
    "PromptFilterResult",
    "AudioTaskLabel",
    "AudioTranscriptionFormat",
    "AudioTranslationFormat",
    "AzureChatExtensionType",
    "ChatRole",
    "CompletionsFinishReason",
    "ContentFilterSeverity",
    "FunctionCallPreset",
    "ImageGenerationResponseFormat",
    "ImageSize",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
