# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models import CompletionsLogProbabilityModel
from ._models import FunctionName
from ._models import ImageLocation
from ._models import ImagePayload

from ._enums import AudioTaskLabel
from ._enums import AudioTranscriptionFormat
from ._enums import AudioTranslationFormat
from ._enums import AzureChatExtensionType
from ._enums import AzureOpenAIOperationState
from ._enums import ChatRole
from ._enums import CompletionsFinishReason
from ._enums import ContentFilterSeverity
from ._enums import FunctionCallPreset
from ._enums import ImageGenerationResponseFormat
from ._enums import ImageSize
from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "CompletionsLogProbabilityModel",
    "FunctionName",
    "ImageLocation",
    "ImagePayload",
    "AudioTaskLabel",
    "AudioTranscriptionFormat",
    "AudioTranslationFormat",
    "AzureChatExtensionType",
    "AzureOpenAIOperationState",
    "ChatRole",
    "CompletionsFinishReason",
    "ContentFilterSeverity",
    "FunctionCallPreset",
    "ImageGenerationResponseFormat",
    "ImageSize",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
