# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ServerEndpointCloudTieringStatus(Model):
    """Server Endpoint cloud tiering status.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar health: Cloud tiering health status. Possible values include:
     'Healthy', 'Error'
    :vartype health: str or ~azure.mgmt.storagesync.models.enum
    :ivar last_updated_timestamp: Last updated timestamp
    :vartype last_updated_timestamp: datetime
    :ivar last_cloud_tiering_result: Last cloud tiering result (HResult)
    :vartype last_cloud_tiering_result: int
    """

    _validation = {
        'health': {'readonly': True},
        'last_updated_timestamp': {'readonly': True},
        'last_cloud_tiering_result': {'readonly': True},
    }

    _attribute_map = {
        'health': {'key': 'health', 'type': 'str'},
        'last_updated_timestamp': {'key': 'lastUpdatedTimestamp', 'type': 'iso-8601'},
        'last_cloud_tiering_result': {'key': 'lastCloudTieringResult', 'type': 'int'},
    }

    def __init__(self, **kwargs) -> None:
        super(ServerEndpointCloudTieringStatus, self).__init__(**kwargs)
        self.health = None
        self.last_updated_timestamp = None
        self.last_cloud_tiering_result = None
