# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ServerEndpointRecallStatus(Model):
    """Server Endpoint recall status.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar last_updated_timestamp: Last updated timestamp
    :vartype last_updated_timestamp: datetime
    :ivar egress_file_count: Egress file count.
    :vartype egress_file_count: long
    :ivar egress_byte_count: Egress byte count.
    :vartype egress_byte_count: long
    :ivar files_not_syncing_errors: Array of errors coming from recall.
    :vartype files_not_syncing_errors:
     list[~azure.mgmt.storagesync.models.ServerEndpointFilesNotRecallingError]
    """

    _validation = {
        'last_updated_timestamp': {'readonly': True},
        'egress_file_count': {'readonly': True},
        'egress_byte_count': {'readonly': True},
        'files_not_syncing_errors': {'readonly': True},
    }

    _attribute_map = {
        'last_updated_timestamp': {'key': 'lastUpdatedTimestamp', 'type': 'iso-8601'},
        'egress_file_count': {'key': 'egressFileCount', 'type': 'long'},
        'egress_byte_count': {'key': 'egressByteCount', 'type': 'long'},
        'files_not_syncing_errors': {'key': 'filesNotSyncingErrors', 'type': '[ServerEndpointFilesNotRecallingError]'},
    }

    def __init__(self, **kwargs):
        super(ServerEndpointRecallStatus, self).__init__(**kwargs)
        self.last_updated_timestamp = None
        self.egress_file_count = None
        self.egress_byte_count = None
        self.files_not_syncing_errors = None
