# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ServerEndpointFilesNotRecallingError(Model):
    """Files not recalling error object.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar error_code: Error code (HResult)
    :vartype error_code: int
    :ivar file_count: Count of files not recalling with the specified error
     code
    :vartype file_count: long
    """

    _validation = {
        'error_code': {'readonly': True},
        'file_count': {'readonly': True},
    }

    _attribute_map = {
        'error_code': {'key': 'errorCode', 'type': 'int'},
        'file_count': {'key': 'fileCount', 'type': 'long'},
    }

    def __init__(self, **kwargs) -> None:
        super(ServerEndpointFilesNotRecallingError, self).__init__(**kwargs)
        self.error_code = None
        self.file_count = None
