# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from ._computer_vision_client_operations import ComputerVisionClientOperationsMixin

__all__ = [
    'ComputerVisionClientOperationsMixin',
]
