# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AnalyzeResult
    from ._models_py3 import AnalyzeResultOperation
    from ._models_py3 import AuthorizeCopyRequest
    from ._models_py3 import AzureBlobContentSource
    from ._models_py3 import Base64ContentSource
    from ._models_py3 import BoundingRegion
    from ._models_py3 import BuildDocumentModelRequest
    from ._models_py3 import ComposeDocumentModelRequest
    from ._models_py3 import ComposeDocumentModelRequestComponentModelsItem
    from ._models_py3 import ContentSource
    from ._models_py3 import CopyAuthorization
    from ._models_py3 import DocTypeInfo
    from ._models_py3 import Document
    from ._models_py3 import DocumentEntity
    from ._models_py3 import DocumentField
    from ._models_py3 import DocumentKeyValueElement
    from ._models_py3 import DocumentKeyValuePair
    from ._models_py3 import DocumentLine
    from ._models_py3 import DocumentPage
    from ._models_py3 import DocumentSelectionMark
    from ._models_py3 import DocumentSpan
    from ._models_py3 import DocumentStyle
    from ._models_py3 import DocumentTable
    from ._models_py3 import DocumentTableCell
    from ._models_py3 import DocumentWord
    from ._models_py3 import Error
    from ._models_py3 import ErrorResponse
    from ._models_py3 import FieldTypeSchema
    from ._models_py3 import GetInfoResponse
    from ._models_py3 import GetInfoResponseCustomDocumentModels
    from ._models_py3 import GetModelsResponse
    from ._models_py3 import GetOperationResponse
    from ._models_py3 import GetOperationsResponse
    from ._models_py3 import InnerError
    from ._models_py3 import LocalContentSource
    from ._models_py3 import ModelInfo
    from ._models_py3 import ModelSummary
    from ._models_py3 import OperationInfo
    from ._models_py3 import WebContentSource
except (SyntaxError, ImportError):
    from ._models import AnalyzeResult  # type: ignore
    from ._models import AnalyzeResultOperation  # type: ignore
    from ._models import AuthorizeCopyRequest  # type: ignore
    from ._models import AzureBlobContentSource  # type: ignore
    from ._models import Base64ContentSource  # type: ignore
    from ._models import BoundingRegion  # type: ignore
    from ._models import BuildDocumentModelRequest  # type: ignore
    from ._models import ComposeDocumentModelRequest  # type: ignore
    from ._models import ComposeDocumentModelRequestComponentModelsItem  # type: ignore
    from ._models import ContentSource  # type: ignore
    from ._models import CopyAuthorization  # type: ignore
    from ._models import DocTypeInfo  # type: ignore
    from ._models import Document  # type: ignore
    from ._models import DocumentEntity  # type: ignore
    from ._models import DocumentField  # type: ignore
    from ._models import DocumentKeyValueElement  # type: ignore
    from ._models import DocumentKeyValuePair  # type: ignore
    from ._models import DocumentLine  # type: ignore
    from ._models import DocumentPage  # type: ignore
    from ._models import DocumentSelectionMark  # type: ignore
    from ._models import DocumentSpan  # type: ignore
    from ._models import DocumentStyle  # type: ignore
    from ._models import DocumentTable  # type: ignore
    from ._models import DocumentTableCell  # type: ignore
    from ._models import DocumentWord  # type: ignore
    from ._models import Error  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import FieldTypeSchema  # type: ignore
    from ._models import GetInfoResponse  # type: ignore
    from ._models import GetInfoResponseCustomDocumentModels  # type: ignore
    from ._models import GetModelsResponse  # type: ignore
    from ._models import GetOperationResponse  # type: ignore
    from ._models import GetOperationsResponse  # type: ignore
    from ._models import InnerError  # type: ignore
    from ._models import LocalContentSource  # type: ignore
    from ._models import ModelInfo  # type: ignore
    from ._models import ModelSummary  # type: ignore
    from ._models import OperationInfo  # type: ignore
    from ._models import WebContentSource  # type: ignore

from ._form_recognizer_client_enums import (
    AnalyzeResultOperationStatus,
    ApiVersion,
    ContentSourceKind,
    ContentType,
    DocumentFieldType,
    DocumentModelBuildTechnique,
    DocumentSignatureType,
    DocumentTableCellKind,
    FieldTypeSchemaType,
    LengthUnit,
    OperationInfoKind,
    OperationStatus,
    SelectionMarkState,
    StringIndexType,
)

__all__ = [
    'AnalyzeResult',
    'AnalyzeResultOperation',
    'AuthorizeCopyRequest',
    'AzureBlobContentSource',
    'Base64ContentSource',
    'BoundingRegion',
    'BuildDocumentModelRequest',
    'ComposeDocumentModelRequest',
    'ComposeDocumentModelRequestComponentModelsItem',
    'ContentSource',
    'CopyAuthorization',
    'DocTypeInfo',
    'Document',
    'DocumentEntity',
    'DocumentField',
    'DocumentKeyValueElement',
    'DocumentKeyValuePair',
    'DocumentLine',
    'DocumentPage',
    'DocumentSelectionMark',
    'DocumentSpan',
    'DocumentStyle',
    'DocumentTable',
    'DocumentTableCell',
    'DocumentWord',
    'Error',
    'ErrorResponse',
    'FieldTypeSchema',
    'GetInfoResponse',
    'GetInfoResponseCustomDocumentModels',
    'GetModelsResponse',
    'GetOperationResponse',
    'GetOperationsResponse',
    'InnerError',
    'LocalContentSource',
    'ModelInfo',
    'ModelSummary',
    'OperationInfo',
    'WebContentSource',
    'AnalyzeResultOperationStatus',
    'ApiVersion',
    'ContentSourceKind',
    'ContentType',
    'DocumentFieldType',
    'DocumentModelBuildTechnique',
    'DocumentSignatureType',
    'DocumentTableCellKind',
    'FieldTypeSchemaType',
    'LengthUnit',
    'OperationInfoKind',
    'OperationStatus',
    'SelectionMarkState',
    'StringIndexType',
]
