# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AnalyzeOperationResult
    from ._models_py3 import AnalyzeResult
    from ._models_py3 import AnalyzeResultAutoGenerated
    from ._models_py3 import AnalyzeResultOperation
    from ._models_py3 import AzureBlobContentSource
    from ._models_py3 import Base64ContentSource
    from ._models_py3 import BoundingRegion
    from ._models_py3 import Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties
    from ._models_py3 import ContentSource
    from ._models_py3 import CopyAuthorization
    from ._models_py3 import CopyAuthorizationResult
    from ._models_py3 import CopyOperationResult
    from ._models_py3 import CopyRequest
    from ._models_py3 import CopyResult
    from ._models_py3 import DataTable
    from ._models_py3 import DataTableCell
    from ._models_py3 import Document
    from ._models_py3 import DocumentEntity
    from ._models_py3 import DocumentKeyValueElement
    from ._models_py3 import DocumentKeyValuePair
    from ._models_py3 import DocumentLine
    from ._models_py3 import DocumentPage
    from ._models_py3 import DocumentResult
    from ._models_py3 import DocumentSelectionMark
    from ._models_py3 import DocumentSpan
    from ._models_py3 import DocumentStyle
    from ._models_py3 import DocumentTable
    from ._models_py3 import DocumentTableCell
    from ._models_py3 import DocumentWord
    from ._models_py3 import Error
    from ._models_py3 import ErrorInformation
    from ._models_py3 import ErrorResponse
    from ._models_py3 import ErrorResponseAutoGenerated
    from ._models_py3 import FieldTypeSchema
    from ._models_py3 import FieldValue
    from ._models_py3 import FieldValueAutoGenerated
    from ._models_py3 import FormFieldsReport
    from ._models_py3 import InnerError
    from ._models_py3 import KeyValueElement
    from ._models_py3 import KeyValuePair
    from ._models_py3 import KeysResult
    from ._models_py3 import LocalContentSource
    from ._models_py3 import Model
    from ._models_py3 import ModelInfo
    from ._models_py3 import ModelInfoAutoGenerated
    from ._models_py3 import ModelSummary
    from ._models_py3 import Models
    from ._models_py3 import ModelsSummary
    from ._models_py3 import OperationInfo
    from ._models_py3 import PageResult
    from ._models_py3 import Paths10VzxpuDocumentmodelsBuildPostRequestbodyContentApplicationJsonSchema
    from ._models_py3 import Paths12Yna0IDocumentmodelsModelidAnalyzePostRequestbodyContentImageJpegSchema
    from ._models_py3 import Paths1A41EsjOperationsOperationidGetResponses200ContentApplicationJsonSchema
    from ._models_py3 import Paths1CndbjaDocumentmodelsGetResponses200ContentApplicationJsonSchema
    from ._models_py3 import Paths1D9IbxeInfoGetResponses200ContentApplicationJsonSchemaPropertiesCustomdocumentmodels
    from ._models_py3 import Paths1Ep1Fe8InfoGetResponses200ContentApplicationJsonSchema
    from ._models_py3 import Paths1F37K28OperationsOperationidGetResponses200ContentApplicationJsonSchemaAllof1
    from ._models_py3 import Paths1Ln1VDocumentmodelsAuthorizecopyPostRequestbodyContentApplicationJsonSchema
    from ._models_py3 import Paths1PlkkrbDocumentmodelsModelidAnalyzePostRequestbodyContentApplicationPdfSchema
    from ._models_py3 import Paths1UuvhddDocumentmodelsModelidAnalyzePostRequestbodyContentImageBmpSchema
    from ._models_py3 import Paths5F1To2DocumentmodelsModelidAnalyzePostRequestbodyContentImageTiffSchema
    from ._models_py3 import Paths8GtshoDocumentmodelsComposePostRequestbodyContentApplicationJsonSchema
    from ._models_py3 import PathsNboob5DocumentmodelsModelidAnalyzePostRequestbodyContentImagePngSchema
    from ._models_py3 import PathsOawoizDocumentmodelsModelidAnalyzePostRequestbodyContentApplicationOctetStreamSchema
    from ._models_py3 import PathsXjehw4DocumentmodelsModelidAnalyzePostRequestbodyContentApplicationJsonSchema
    from ._models_py3 import PathsY4MxprOperationsGetResponses200ContentApplicationJsonSchema
    from ._models_py3 import PostContentSchemaComponentModelsItem
    from ._models_py3 import ReadResult
    from ._models_py3 import SourcePath
    from ._models_py3 import TextLine
    from ._models_py3 import TextWord
    from ._models_py3 import TrainRequest
    from ._models_py3 import TrainResult
    from ._models_py3 import TrainSourceFilter
    from ._models_py3 import TrainingDocumentInfo
    from ._models_py3 import WebContentSource
except (SyntaxError, ImportError):
    from ._models import AnalyzeOperationResult  # type: ignore
    from ._models import AnalyzeResult  # type: ignore
    from ._models import AnalyzeResultAutoGenerated  # type: ignore
    from ._models import AnalyzeResultOperation  # type: ignore
    from ._models import AzureBlobContentSource  # type: ignore
    from ._models import Base64ContentSource  # type: ignore
    from ._models import BoundingRegion  # type: ignore
    from ._models import Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties  # type: ignore
    from ._models import ContentSource  # type: ignore
    from ._models import CopyAuthorization  # type: ignore
    from ._models import CopyAuthorizationResult  # type: ignore
    from ._models import CopyOperationResult  # type: ignore
    from ._models import CopyRequest  # type: ignore
    from ._models import CopyResult  # type: ignore
    from ._models import DataTable  # type: ignore
    from ._models import DataTableCell  # type: ignore
    from ._models import Document  # type: ignore
    from ._models import DocumentEntity  # type: ignore
    from ._models import DocumentKeyValueElement  # type: ignore
    from ._models import DocumentKeyValuePair  # type: ignore
    from ._models import DocumentLine  # type: ignore
    from ._models import DocumentPage  # type: ignore
    from ._models import DocumentResult  # type: ignore
    from ._models import DocumentSelectionMark  # type: ignore
    from ._models import DocumentSpan  # type: ignore
    from ._models import DocumentStyle  # type: ignore
    from ._models import DocumentTable  # type: ignore
    from ._models import DocumentTableCell  # type: ignore
    from ._models import DocumentWord  # type: ignore
    from ._models import Error  # type: ignore
    from ._models import ErrorInformation  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import ErrorResponseAutoGenerated  # type: ignore
    from ._models import FieldTypeSchema  # type: ignore
    from ._models import FieldValue  # type: ignore
    from ._models import FieldValueAutoGenerated  # type: ignore
    from ._models import FormFieldsReport  # type: ignore
    from ._models import InnerError  # type: ignore
    from ._models import KeyValueElement  # type: ignore
    from ._models import KeyValuePair  # type: ignore
    from ._models import KeysResult  # type: ignore
    from ._models import LocalContentSource  # type: ignore
    from ._models import Model  # type: ignore
    from ._models import ModelInfo  # type: ignore
    from ._models import ModelInfoAutoGenerated  # type: ignore
    from ._models import ModelSummary  # type: ignore
    from ._models import Models  # type: ignore
    from ._models import ModelsSummary  # type: ignore
    from ._models import OperationInfo  # type: ignore
    from ._models import PageResult  # type: ignore
    from ._models import Paths10VzxpuDocumentmodelsBuildPostRequestbodyContentApplicationJsonSchema  # type: ignore
    from ._models import Paths12Yna0IDocumentmodelsModelidAnalyzePostRequestbodyContentImageJpegSchema  # type: ignore
    from ._models import Paths1A41EsjOperationsOperationidGetResponses200ContentApplicationJsonSchema  # type: ignore
    from ._models import Paths1CndbjaDocumentmodelsGetResponses200ContentApplicationJsonSchema  # type: ignore
    from ._models import Paths1D9IbxeInfoGetResponses200ContentApplicationJsonSchemaPropertiesCustomdocumentmodels  # type: ignore
    from ._models import Paths1Ep1Fe8InfoGetResponses200ContentApplicationJsonSchema  # type: ignore
    from ._models import Paths1F37K28OperationsOperationidGetResponses200ContentApplicationJsonSchemaAllof1  # type: ignore
    from ._models import Paths1Ln1VDocumentmodelsAuthorizecopyPostRequestbodyContentApplicationJsonSchema  # type: ignore
    from ._models import Paths1PlkkrbDocumentmodelsModelidAnalyzePostRequestbodyContentApplicationPdfSchema  # type: ignore
    from ._models import Paths1UuvhddDocumentmodelsModelidAnalyzePostRequestbodyContentImageBmpSchema  # type: ignore
    from ._models import Paths5F1To2DocumentmodelsModelidAnalyzePostRequestbodyContentImageTiffSchema  # type: ignore
    from ._models import Paths8GtshoDocumentmodelsComposePostRequestbodyContentApplicationJsonSchema  # type: ignore
    from ._models import PathsNboob5DocumentmodelsModelidAnalyzePostRequestbodyContentImagePngSchema  # type: ignore
    from ._models import PathsOawoizDocumentmodelsModelidAnalyzePostRequestbodyContentApplicationOctetStreamSchema  # type: ignore
    from ._models import PathsXjehw4DocumentmodelsModelidAnalyzePostRequestbodyContentApplicationJsonSchema  # type: ignore
    from ._models import PathsY4MxprOperationsGetResponses200ContentApplicationJsonSchema  # type: ignore
    from ._models import PostContentSchemaComponentModelsItem  # type: ignore
    from ._models import ReadResult  # type: ignore
    from ._models import SourcePath  # type: ignore
    from ._models import TextLine  # type: ignore
    from ._models import TextWord  # type: ignore
    from ._models import TrainRequest  # type: ignore
    from ._models import TrainResult  # type: ignore
    from ._models import TrainSourceFilter  # type: ignore
    from ._models import TrainingDocumentInfo  # type: ignore
    from ._models import WebContentSource  # type: ignore

from ._form_recognizer_client_enums import (
    AnalyzeResultOperationStatus,
    ApiVersion,
    ContentSourceKind,
    ContentType,
    ContentType1,
    DocumentModelBuildTechnique,
    DocumentSignatureType,
    DocumentTableCellKind,
    FieldTypeSchemaType,
    FieldValueType,
    Language,
    LengthUnit,
    ModelStatus,
    OperationInfoKind,
    OperationStatus,
    SelectionMarkState,
    StringIndexType,
    TrainStatus,
)

__all__ = [
    'AnalyzeOperationResult',
    'AnalyzeResult',
    'AnalyzeResultAutoGenerated',
    'AnalyzeResultOperation',
    'AzureBlobContentSource',
    'Base64ContentSource',
    'BoundingRegion',
    'Components70NzpzSchemasModelinfoPropertiesDoctypesAdditionalproperties',
    'ContentSource',
    'CopyAuthorization',
    'CopyAuthorizationResult',
    'CopyOperationResult',
    'CopyRequest',
    'CopyResult',
    'DataTable',
    'DataTableCell',
    'Document',
    'DocumentEntity',
    'DocumentKeyValueElement',
    'DocumentKeyValuePair',
    'DocumentLine',
    'DocumentPage',
    'DocumentResult',
    'DocumentSelectionMark',
    'DocumentSpan',
    'DocumentStyle',
    'DocumentTable',
    'DocumentTableCell',
    'DocumentWord',
    'Error',
    'ErrorInformation',
    'ErrorResponse',
    'ErrorResponseAutoGenerated',
    'FieldTypeSchema',
    'FieldValue',
    'FieldValueAutoGenerated',
    'FormFieldsReport',
    'InnerError',
    'KeyValueElement',
    'KeyValuePair',
    'KeysResult',
    'LocalContentSource',
    'Model',
    'ModelInfo',
    'ModelInfoAutoGenerated',
    'ModelSummary',
    'Models',
    'ModelsSummary',
    'OperationInfo',
    'PageResult',
    'Paths10VzxpuDocumentmodelsBuildPostRequestbodyContentApplicationJsonSchema',
    'Paths12Yna0IDocumentmodelsModelidAnalyzePostRequestbodyContentImageJpegSchema',
    'Paths1A41EsjOperationsOperationidGetResponses200ContentApplicationJsonSchema',
    'Paths1CndbjaDocumentmodelsGetResponses200ContentApplicationJsonSchema',
    'Paths1D9IbxeInfoGetResponses200ContentApplicationJsonSchemaPropertiesCustomdocumentmodels',
    'Paths1Ep1Fe8InfoGetResponses200ContentApplicationJsonSchema',
    'Paths1F37K28OperationsOperationidGetResponses200ContentApplicationJsonSchemaAllof1',
    'Paths1Ln1VDocumentmodelsAuthorizecopyPostRequestbodyContentApplicationJsonSchema',
    'Paths1PlkkrbDocumentmodelsModelidAnalyzePostRequestbodyContentApplicationPdfSchema',
    'Paths1UuvhddDocumentmodelsModelidAnalyzePostRequestbodyContentImageBmpSchema',
    'Paths5F1To2DocumentmodelsModelidAnalyzePostRequestbodyContentImageTiffSchema',
    'Paths8GtshoDocumentmodelsComposePostRequestbodyContentApplicationJsonSchema',
    'PathsNboob5DocumentmodelsModelidAnalyzePostRequestbodyContentImagePngSchema',
    'PathsOawoizDocumentmodelsModelidAnalyzePostRequestbodyContentApplicationOctetStreamSchema',
    'PathsXjehw4DocumentmodelsModelidAnalyzePostRequestbodyContentApplicationJsonSchema',
    'PathsY4MxprOperationsGetResponses200ContentApplicationJsonSchema',
    'PostContentSchemaComponentModelsItem',
    'ReadResult',
    'SourcePath',
    'TextLine',
    'TextWord',
    'TrainRequest',
    'TrainResult',
    'TrainSourceFilter',
    'TrainingDocumentInfo',
    'WebContentSource',
    'AnalyzeResultOperationStatus',
    'ApiVersion',
    'ContentSourceKind',
    'ContentType',
    'ContentType1',
    'DocumentModelBuildTechnique',
    'DocumentSignatureType',
    'DocumentTableCellKind',
    'FieldTypeSchemaType',
    'FieldValueType',
    'Language',
    'LengthUnit',
    'ModelStatus',
    'OperationInfoKind',
    'OperationStatus',
    'SelectionMarkState',
    'StringIndexType',
    'TrainStatus',
]
