# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6198, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum

class ModelStatus(str, Enum):

    creating = "creating"
    ready = "ready"
    invalid = "invalid"

class TrainStatus(str, Enum):

    succeeded = "succeeded"
    partially_succeeded = "partiallySucceeded"
    failed = "failed"

class Language(str, Enum):

    en = "en"
    es = "es"

class LengthUnit(str, Enum):

    pixel = "pixel"
    inch = "inch"

class FieldValueType(str, Enum):

    string = "string"
    date_enum = "date"
    time = "time"
    phone_number = "phoneNumber"
    number = "number"
    integer = "integer"
    array = "array"
    object_enum = "object"

class Enum0(str, Enum):

    full = "full"
    summary = "summary"

class OperationStatus(str, Enum):

    not_started = "notStarted"
    running = "running"
    succeeded = "succeeded"
    failed = "failed"
