name: Copilot Setup Steps

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Ensure virtualenv installed
        run: python -m pip install virtualenv

      - name: Create and activate virtual environment
        run: |
          python -m virtualenv .venv
          echo "VIRTUAL_ENV=$(pwd)/.venv" >> $GITHUB_ENV
          echo "$(pwd)/.venv/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          python -m pip install -r eng/ci_tools.txt
          python -m pip install pip==20.3.3 setuptools==59.6.0 wheel==0.37.0
